### PR TITLE
[DS-287]: [Pyxis Elm] RadioCardGroup and CheckboxCardGroup refactoring

### PR DESCRIPTION
**Pull request by Gsciarra**
https://prima-assicurazioni-spa.myjetbrains.com/youtrack/issue/DS-287

# 💥 Breaking Change
Modules `RadioCardGroup` and  `CheckboxCardGroup` are removed. Now you can use `RadioGroup` and `CheckboxGroup` to create the `Card` variant too.
```Elm
-- OLD
CheckboxCardGroup.config "checkboxCardGroup-name"
        |> CheckboxCardGroup.withOptions
            [ CheckboxCardGroup.option
                { value = Motor
                , title = Just "Motor"
                , text = Just "Lorem ipsum dolor"
                , addon = Nothing
                }
            , CheckboxCardGroup.option
                { value = Household
                , title = Just "Home"
                , text = Just "Lorem ipsum dolor"
                , addon = Nothing
                }
            ]

--- NEW
CheckboxGroup.config "checkboxGroup-name"
        |> CheckboxCardGroup.withOptionsCard
            [ CheckboxCardGroup.optionCardMedium
                { value = Motor
                , title = Just "Motor"
                , text = Just "Lorem ipsum dolor"
                , addon = Nothing
                }
            , CheckboxCardGroup.optionCardMedium
                { value = Household
                , title = Just "Home"
                , text = Just "Lorem ipsum dolor"
                , addon = Nothing
                }
            ]

```

### CODE REVIEW

**Review by emanuelemacri — CHANGES_REQUESTED** [review]
Everything looks good to me, even docs and examples. I only suggested a small visual fix

**Review by brianvanburken — APPROVED** [review]
LGTM

**Review by emanuelemacri — APPROVED** [review]
LGTM

**Review by lauratrapani — CHANGES_REQUESTED** [review]
The implementation for me is ok. I just have some doubts about the fact that in React and Design part the RadioCardGroup and CheckboxCardGroup are different from RadioGroup and CheckboxGroup, so I was wondering if it could be better to keep the documentation of each Group and the corresponding CardGroup separated.

Also, a detailed description containing a brief changelog should be added to this PR.

**Review by alessiosantangelo — APPROVED** [review]

**Review by lauratrapani — APPROVED** [review]

**Pull request merged**
